
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer
  namespace: testgrid
  labels:
    component: summarizer
    app: testgrid
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: summarizer
        app: testgrid
    spec:
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/testgrid/summarizer
        args:
        - --config=gs://k8s-testgrid/beta/config
        - --wait=5m
        #- --confirm
