
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-summarizer
  namespace: testgrid
  labels:
    component: summarizer
    app: testgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: summarizer
  template:
    metadata:
      labels:
        component: summarizer
        app: testgrid
    spec:
      serviceAccountName: summarizer
      containers:
      - name: summarizer
        image: gcr.io/k8s-testgrid/summarizer:v20191212-v0.0.1-alpha.3-39-g6fa4a42
        args:
        - --config=gs://k8s-testgrid/config
        - --confirm
        - --wait=5m
