
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-updater
  namespace: testgrid
  labels:
    component: updater
    app: testgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      component: updater
  template:
    metadata:
      labels:
        component: updater
        app: testgrid
    spec:
      containers:
      - name: updater
        image: gcr.io/k8s-testgrid/updater:v20191122-v0.0.1-alpha.2-13-g31a8cc8
        args:
        - --config=gs://k8s-testgrid/beta/config
        - --wait=5m
        #- --confirm
